/**
 * Stress test for terminaltui CLI templates.
 * Verifies that every CLI template (minimal, portfolio, landing, restaurant, blog, creative)
 * generates valid configs that parse and render correctly.
 *
 * Run with: npx tsx test/stress-templates.ts
 */
import {
  createTestContext,
  assert,
  assertNoThrow,
  assertLines,
  assertLinesNonEmpty,
  assertNoOverflow,
  renderBlock,
  defineSite,
  page,
  card,
  timeline,
  table,
  list,
  quote,
  hero,
  link,
  skillBar,
  markdown,
  divider,
  spacer,
  section,
  ascii,
  themes,
  type TestResult,
} from "./harness.js";

import { renderBanner } from "../src/ascii/banner.js";
import { gradientLines } from "../src/style/gradient.js";
import { stripAnsi } from "../src/components/base.js";
import type { SiteConfig, ContentBlock, Site } from "../src/config/types.js";
import type { Theme } from "../src/style/theme.js";

// ─── Test Infrastructure ──────────────────────────────────

const results: TestResult[] = [];

function test(name: string, fn: () => void): void {
  try {
    fn();
    results.push({ name, passed: true });
  } catch (err: any) {
    results.push({ name, passed: false, error: err.message });
  }
}

// ─── Template Config Builders ─────────────────────────────
// These replicate the configs generated by each CLI template in init.ts,
// using the framework API directly instead of eval-ing generated strings.

interface TemplateInfo {
  name: string;
  expectedPages: number;
  hasBanner: boolean;
  bannerFont: string;
  bannerGradient?: string[];
  hasAnimations: boolean;
  config: SiteConfig;
}

function buildMinimalConfig(): TemplateInfo {
  const siteName = "TestMinimal";
  const tagline = "welcome to my terminal";
  const config: SiteConfig = {
    name: siteName,
    tagline,
    banner: ascii(siteName, { font: "ANSI Shadow" }),
    theme: themes.dracula,
    pages: [
      page("about", {
        title: "About",
        icon: "◆",
        content: [
          markdown("Hello! Edit site.config.ts to customize this site."),
        ],
      }),
      page("links", {
        title: "Links",
        icon: "◉",
        content: [
          link("GitHub", "https://github.com"),
          link("Website", "https://example.com"),
        ],
      }),
    ],
  };
  return {
    name: "minimal",
    expectedPages: 2,
    hasBanner: true,
    bannerFont: "ANSI Shadow",
    hasAnimations: false,
    config,
  };
}

function buildPortfolioConfig(): TemplateInfo {
  const siteName = "TestPortfolio";
  const tagline = "software engineer";
  const config: SiteConfig = {
    name: siteName,
    tagline,
    banner: ascii(siteName, { font: "ANSI Shadow", gradient: ["#ff6b6b", "#4ecdc4"] }),
    theme: themes.dracula,
    animations: { boot: true, transitions: "fade" },
    pages: [
      page("about", {
        title: "About",
        icon: "◆",
        content: [
          markdown("Hey! I build things. Edit this file to tell your story."),
        ],
      }),
      page("projects", {
        title: "Projects",
        icon: "◈",
        content: [
          card({ title: "Project One", subtitle: "★ 100", body: "A cool project", tags: ["TypeScript"], url: "https://github.com" }),
          card({ title: "Project Two", subtitle: "★ 50", body: "Another project", tags: ["Rust"], url: "https://github.com" }),
        ],
      }),
      page("experience", {
        title: "Experience",
        icon: "▣",
        content: [
          timeline([
            { title: "Senior Engineer", subtitle: "Company", period: "2023 — present", description: "Leading projects" },
            { title: "Software Engineer", subtitle: "Startup", period: "2021 — 2023", description: "Full-stack development" },
          ]),
        ],
      }),
      page("skills", {
        title: "Skills",
        icon: "▤",
        content: [
          skillBar("TypeScript", 90),
          skillBar("Rust", 75),
          skillBar("Python", 80),
          skillBar("Go", 65),
        ],
      }),
      page("links", {
        title: "Links",
        icon: "◉",
        content: [
          link("GitHub", "https://github.com"),
          link("LinkedIn", "https://linkedin.com"),
          link("Email", "mailto:hello@example.com"),
        ],
      }),
    ],
  };
  return {
    name: "portfolio",
    expectedPages: 5,
    hasBanner: true,
    bannerFont: "ANSI Shadow",
    bannerGradient: ["#ff6b6b", "#4ecdc4"],
    hasAnimations: true,
    config,
  };
}

function buildLandingConfig(): TemplateInfo {
  const siteName = "TestLanding";
  const tagline = "the future is here";
  const config: SiteConfig = {
    name: siteName,
    tagline,
    banner: ascii(siteName, { font: "ANSI Shadow", gradient: ["#7c3aed", "#06b6d4"] }),
    theme: themes.dracula,
    animations: { boot: true, transitions: "slide" },
    pages: [
      page("home", {
        title: "Home",
        icon: "◆",
        content: [
          hero({ title: `Welcome to ${siteName}`, subtitle: tagline, cta: { label: "Get Started →", url: "https://example.com" } }),
        ],
      }),
      page("features", {
        title: "Features",
        icon: "◈",
        content: [
          card({ title: "Feature One", body: "Description of your first feature", tags: ["Core"] }),
          card({ title: "Feature Two", body: "Description of your second feature", tags: ["Pro"] }),
          card({ title: "Feature Three", body: "Description of your third feature", tags: ["Enterprise"] }),
        ],
      }),
      page("pricing", {
        title: "Pricing",
        icon: "▣",
        content: [
          table(["Plan", "Price", "Features"], [
            ["Free", "$0/mo", "Basic features"],
            ["Pro", "$10/mo", "Everything in Free + more"],
            ["Enterprise", "Custom", "Unlimited everything"],
          ]),
        ],
      }),
      page("docs", {
        title: "Quick Start",
        icon: "▸",
        content: [
          list(["Install the package", "Configure your settings", "Deploy to production"], "number"),
          link("Full Documentation →", "https://docs.example.com"),
        ],
      }),
    ],
  };
  return {
    name: "landing",
    expectedPages: 4,
    hasBanner: true,
    bannerFont: "ANSI Shadow",
    bannerGradient: ["#7c3aed", "#06b6d4"],
    hasAnimations: true,
    config,
  };
}

function buildRestaurantConfig(): TemplateInfo {
  const siteName = "TestRestaurant";
  const tagline = "fine dining experience";
  const config: SiteConfig = {
    name: siteName,
    tagline,
    banner: ascii(siteName, { font: "Ogre", gradient: ["#d4a373", "#e63946"] }),
    theme: themes.dracula,
    borders: "rounded",
    animations: { boot: true, transitions: "fade", exitMessage: "Thanks for visiting! See you at the table." },
    pages: [
      page("menu", {
        title: "Menu",
        icon: "◆",
        content: [
          section("Starters", [
            card({ title: "Appetizer One", subtitle: "$12", body: "Description of this dish" }),
            card({ title: "Appetizer Two", subtitle: "$14", body: "Description of this dish" }),
          ]),
          divider(),
          section("Mains", [
            card({ title: "Main Course One", subtitle: "$28", body: "Description of this dish" }),
            card({ title: "Main Course Two", subtitle: "$32", body: "Description of this dish" }),
          ]),
        ],
      }),
      page("about", {
        title: "Our Story",
        icon: "◈",
        content: [
          markdown("Tell the story of your restaurant here."),
          divider(),
          quote("A wonderful dining experience.", "— Food Critic"),
        ],
      }),
      page("hours", {
        title: "Hours & Location",
        icon: "▣",
        content: [
          table(["Day", "Hours"], [
            ["Mon — Fri", "11:00 AM — 10:00 PM"],
            ["Sat — Sun", "10:00 AM — 11:00 PM"],
          ]),
          divider(),
          markdown("**Address:** 123 Main Street, Your City"),
          link("Google Maps", "https://maps.google.com"),
          link("Reservations", "https://opentable.com"),
        ],
      }),
      page("contact", {
        title: "Contact",
        icon: "◉",
        content: [
          link("Instagram", "https://instagram.com"),
          link("Phone", "tel:+15551234567"),
          link("Email", "mailto:hello@restaurant.com"),
        ],
      }),
    ],
  };
  return {
    name: "restaurant",
    expectedPages: 4,
    hasBanner: true,
    bannerFont: "Ogre",
    bannerGradient: ["#d4a373", "#e63946"],
    hasAnimations: true,
    config,
  };
}

function buildBlogConfig(): TemplateInfo {
  const siteName = "TestBlog";
  const tagline = "thoughts and writing";
  const config: SiteConfig = {
    name: siteName,
    tagline,
    banner: ascii(siteName, { font: "Small", gradient: ["#ebbcba", "#c4a7e7"] }),
    theme: themes.dracula,
    pages: [
      page("posts", {
        title: "Posts",
        icon: "◆",
        content: [
          card({ title: "My First Post", subtitle: "Mar 2026", body: "A brief summary of what this post is about..." }),
          card({ title: "Another Post", subtitle: "Feb 2026", body: "More interesting thoughts..." }),
        ],
      }),
      page("about", {
        title: "About",
        icon: "◈",
        content: [
          markdown("Write about yourself and your blog here."),
        ],
      }),
      page("links", {
        title: "Links",
        icon: "◉",
        content: [
          link("RSS Feed", "https://example.com/feed"),
          link("Twitter", "https://twitter.com"),
          link("GitHub", "https://github.com"),
        ],
      }),
    ],
  };
  return {
    name: "blog",
    expectedPages: 3,
    hasBanner: true,
    bannerFont: "Small",
    bannerGradient: ["#ebbcba", "#c4a7e7"],
    hasAnimations: false,
    config,
  };
}

function buildCreativeConfig(): TemplateInfo {
  const siteName = "TestCreative";
  const tagline = "experiment · create · explore";
  const config: SiteConfig = {
    name: siteName,
    tagline,
    banner: ascii(siteName, { font: "Slant", gradient: ["#ff2a6d", "#05d9e8", "#ff2a6d"] }),
    theme: themes.dracula,
    animations: { boot: true, transitions: "wipe", exitMessage: "[ end of transmission ]" },
    pages: [
      page("enter", {
        title: "Enter",
        icon: "✦",
        content: [
          spacer(2),
          markdown("Welcome to the void. This is your creative space."),
          spacer(),
          divider("dotted"),
          spacer(),
          markdown("Edit **site.config.ts** to make it yours."),
        ],
      }),
      page("links", {
        title: "Links",
        icon: "◉",
        content: [
          link("The Source", "https://github.com"),
        ],
      }),
    ],
  };
  return {
    name: "creative",
    expectedPages: 2,
    hasBanner: true,
    bannerFont: "Slant",
    bannerGradient: ["#ff2a6d", "#05d9e8", "#ff2a6d"],
    hasAnimations: true,
    config,
  };
}

// ─── All Templates ────────────────────────────────────────

const allTemplates: TemplateInfo[] = [
  buildMinimalConfig(),
  buildPortfolioConfig(),
  buildLandingConfig(),
  buildRestaurantConfig(),
  buildBlogConfig(),
  buildCreativeConfig(),
];

// ─── Per-Template Tests ───────────────────────────────────

interface TemplateSummary {
  template: string;
  total: number;
  passed: number;
  failed: number;
  tests: TestResult[];
}

const summaries: TemplateSummary[] = [];

for (const tpl of allTemplates) {
  const templateResults: TestResult[] = [];

  function ttest(name: string, fn: () => void): void {
    const fullName = `[${tpl.name}] ${name}`;
    try {
      fn();
      templateResults.push({ name: fullName, passed: true });
      results.push({ name: fullName, passed: true });
    } catch (err: any) {
      templateResults.push({ name: fullName, passed: false, error: err.message });
      results.push({ name: fullName, passed: false, error: err.message });
    }
  }

  // Test 1: defineSite() does not throw
  let site: Site | null = null;
  ttest("defineSite() parses without error", () => {
    site = defineSite(tpl.config);
    assert(!!site, "defineSite should return a Site object");
  });

  if (!site) {
    summaries.push({
      template: tpl.name,
      total: 1,
      passed: 0,
      failed: 1,
      tests: templateResults,
    });
    continue;
  }

  // Test 2: Page count matches expected
  ttest(`page count is ${tpl.expectedPages}`, () => {
    assert(
      tpl.config.pages.length === tpl.expectedPages,
      `Expected ${tpl.expectedPages} pages, got ${tpl.config.pages.length}`
    );
  });

  // Test 3: All page IDs are unique and non-empty
  ttest("page IDs are unique and non-empty", () => {
    const ids = new Set<string>();
    for (const pg of tpl.config.pages) {
      assert(!!pg.id, `Page missing id: ${pg.title}`);
      assert(!ids.has(pg.id), `Duplicate page id: ${pg.id}`);
      ids.add(pg.id);
    }
  });

  // Test 4: Theme is valid
  ttest("theme is valid", () => {
    const theme = tpl.config.theme as Theme;
    assert(!!theme, "Theme should be defined");
    assert(!!theme.accent, "Theme missing accent color");
    assert(!!theme.text, "Theme missing text color");
    assert(!!theme.border, "Theme missing border color");
    assert(!!theme.muted, "Theme missing muted color");
  });

  // Test 5: Banner renders
  if (tpl.hasBanner) {
    ttest("banner renders", () => {
      const banner = tpl.config.banner!;
      const bannerLines = renderBanner(banner.text, { font: banner.font });
      assert(bannerLines.length > 0, "Banner should produce output lines");
      const hasContent = bannerLines.some(l => l.trim().length > 0);
      assert(hasContent, "Banner should have non-empty content");
    });

    if (tpl.bannerGradient) {
      ttest("banner gradient applies", () => {
        const banner = tpl.config.banner!;
        const bannerLines = renderBanner(banner.text, { font: banner.font });
        const colored = gradientLines(bannerLines, tpl.bannerGradient!);
        assert(colored.length === bannerLines.length, "Gradient should preserve line count");
        // Gradient lines should contain ANSI escape codes
        const hasAnsi = colored.some(l => l.includes("\x1b["));
        assert(hasAnsi, "Gradient lines should contain ANSI color codes");
      });
    }
  }

  // Test 6: All pages render at width 80 without overflow
  ttest("all pages render at width 80", () => {
    const ctx = createTestContext(80, tpl.config.theme as Theme);
    for (const pg of tpl.config.pages) {
      for (const block of pg.content) {
        const lines = renderBlock(block, ctx);
        assert(Array.isArray(lines), `Block type '${block.type}' on page '${pg.id}' should return array`);
        // Non-spacer blocks should produce output
        if (block.type !== "spacer") {
          assert(lines.length > 0, `Block type '${block.type}' on page '${pg.id}' should produce output at width 80`);
        }
      }
    }
  });

  // Test 7: Check for overflow at width 80
  ttest("no overflow at width 80", () => {
    const ctx = createTestContext(80, tpl.config.theme as Theme);
    for (const pg of tpl.config.pages) {
      for (const block of pg.content) {
        const lines = renderBlock(block, ctx);
        for (let i = 0; i < lines.length; i++) {
          const plainLen = stripAnsi(lines[i]).length;
          if (plainLen > 82) { // +2 tolerance
            throw new Error(
              `Overflow on page '${pg.id}', block '${block.type}', line ${i}: ` +
              `${plainLen} chars (max 80). Content: "${stripAnsi(lines[i]).substring(0, 60)}..."`
            );
          }
        }
      }
    }
  });

  // Test 8: Check for overflow at width 40
  ttest("no overflow at width 40", () => {
    const ctx = createTestContext(40, tpl.config.theme as Theme);
    for (const pg of tpl.config.pages) {
      for (const block of pg.content) {
        const lines = renderBlock(block, ctx);
        for (let i = 0; i < lines.length; i++) {
          const plainLen = stripAnsi(lines[i]).length;
          if (plainLen > 42) { // +2 tolerance
            throw new Error(
              `Overflow on page '${pg.id}', block '${block.type}', line ${i}: ` +
              `${plainLen} chars (max 40). Content: "${stripAnsi(lines[i]).substring(0, 40)}..."`
            );
          }
        }
      }
    }
  });

  // Test 9: All content blocks produce output (non-spacer)
  ttest("all content blocks produce output", () => {
    const ctx = createTestContext(80, tpl.config.theme as Theme);
    let totalBlocks = 0;
    let producingBlocks = 0;
    for (const pg of tpl.config.pages) {
      for (const block of pg.content) {
        totalBlocks++;
        const lines = renderBlock(block, ctx);
        if (lines.length > 0) producingBlocks++;
        // Spacers produce empty lines which is their job
        if (block.type !== "spacer") {
          assert(lines.length > 0,
            `Block '${block.type}' on page '${pg.id}' produced 0 lines`);
        }
      }
    }
    assert(producingBlocks > 0, `At least some blocks should produce output (${producingBlocks}/${totalBlocks})`);
  });

  // Test 10: Animations config is valid (if present)
  if (tpl.hasAnimations) {
    ttest("animations config is valid", () => {
      const anims = tpl.config.animations!;
      assert(anims.boot === true, "boot should be true");
      const validTransitions = ["instant", "fade", "slide", "wipe"];
      assert(
        validTransitions.includes(anims.transitions!),
        `transitions should be one of ${validTransitions.join(", ")}, got '${anims.transitions}'`
      );
    });
  }

  // Test 11: Render at multiple widths (stress check)
  for (const width of [30, 60, 100, 120]) {
    ttest(`all blocks render at width ${width}`, () => {
      const ctx = createTestContext(width, tpl.config.theme as Theme);
      for (const pg of tpl.config.pages) {
        for (const block of pg.content) {
          const lines = renderBlock(block, ctx);
          assert(Array.isArray(lines), `Block '${block.type}' at width ${width} should return array`);
        }
      }
    });
  }

  // Test 12: Content text is preserved in render output
  ttest("content text is present in rendered output", () => {
    const ctx = createTestContext(80, tpl.config.theme as Theme);
    for (const pg of tpl.config.pages) {
      for (const block of pg.content) {
        const lines = renderBlock(block, ctx);
        const text = lines.map(l => stripAnsi(l)).join("\n");
        // Verify some content from the block appears in the output
        if (block.type === "text" && block.content.length > 0) {
          // For markdown/text blocks, at least part of the content should appear
          const snippet = block.content.substring(0, 10).replace(/[*_#]/g, "");
          if (snippet.trim().length > 3) {
            assert(
              text.includes(snippet.trim()),
              `Text content "${snippet.trim()}" not found in rendered output on page '${pg.id}'`
            );
          }
        }
        if (block.type === "card" && block.title.length > 0) {
          assert(
            text.includes(block.title),
            `Card title "${block.title}" not found in rendered output on page '${pg.id}'`
          );
        }
        if (block.type === "link") {
          assert(
            text.includes(block.label),
            `Link label "${block.label}" not found in rendered output on page '${pg.id}'`
          );
        }
      }
    }
  });

  // Collect summary
  const passed = templateResults.filter(r => r.passed).length;
  const failed = templateResults.filter(r => !r.passed).length;
  summaries.push({
    template: tpl.name,
    total: templateResults.length,
    passed,
    failed,
    tests: templateResults,
  });
}

// ─── Cross-Template Tests ─────────────────────────────────

test("Cross-template: all 6 templates build successfully", () => {
  assert(allTemplates.length === 6, `Expected 6 templates, got ${allTemplates.length}`);
  for (const tpl of allTemplates) {
    const site = defineSite(tpl.config);
    assert(!!site, `Template '${tpl.name}' should produce a valid site`);
  }
});

test("Cross-template: every template uses a different banner font or gradient", () => {
  const bannerKeys = allTemplates.map(t => {
    const g = t.bannerGradient ? t.bannerGradient.join(",") : "none";
    return `${t.bannerFont}|${g}`;
  });
  const unique = new Set(bannerKeys);
  assert(
    unique.size === allTemplates.length,
    `Expected ${allTemplates.length} unique banner configs, got ${unique.size}: ${[...unique].join("; ")}`
  );
});

test("Cross-template: all template names are unique", () => {
  const names = allTemplates.map(t => t.name);
  const unique = new Set(names);
  assert(unique.size === allTemplates.length, "Template names should be unique");
});

// ─── Summary Output ───────────────────────────────────────

const totalPassed = results.filter(r => r.passed).length;
const totalFailed = results.filter(r => !r.passed).length;

console.log("\n" + "=".repeat(70));
console.log("STRESS TEST: CLI Template Validation");
console.log("=".repeat(70));

// Per-template summary
for (const summary of summaries) {
  const status = summary.failed === 0 ? "PASS" : "FAIL";
  console.log(`\n--- Template: ${summary.template} [${status}] (${summary.passed}/${summary.total}) ---`);
  for (const r of summary.tests) {
    const icon = r.passed ? "\u2713" : "\u2717";
    const st = r.passed ? "PASS" : "FAIL";
    let line = `  ${icon} [${st}] ${r.name}`;
    if (r.error) line += `\n           Error: ${r.error}`;
    console.log(line);
  }
}

// Cross-template tests
console.log("\n--- Cross-Template Tests ---");
const crossTests = results.filter(r => !r.name.startsWith("["));
for (const r of crossTests) {
  const icon = r.passed ? "\u2713" : "\u2717";
  const st = r.passed ? "PASS" : "FAIL";
  let line = `  ${icon} [${st}] ${r.name}`;
  if (r.error) line += `\n           Error: ${r.error}`;
  console.log(line);
}

console.log("\n" + "=".repeat(70));
console.log(`TOTAL: ${results.length} | PASSED: ${totalPassed} | FAILED: ${totalFailed}`);
console.log("=".repeat(70));

if (totalFailed > 0) {
  console.log("\nFailed tests:");
  for (const r of results.filter(r => !r.passed)) {
    console.log(`  - ${r.name}: ${r.error}`);
  }
}

console.log("\n" + (totalFailed === 0 ? "ALL TESTS PASSED" : `${totalFailed} TEST(S) FAILED`) + "\n");
process.exit(totalFailed > 0 ? 1 : 0);
