#!/usr/bin/env bash
#
# Fetch and derive the video engine's test media.
#
# Same arrangement as the VHS tapes next door: the recipe is committed, the
# megabytes are not (devnotes/media/ is gitignored). Run this from the repo root
# to rebuild everything the video work is developed against.
#
# The tiny deterministic clips under test/fixtures/video/ are NOT produced here —
# those are committed, because a test suite that has to download something is a
# test suite that fails on a plane. They are regenerated by the last section
# below only if you deliberately need to.
#
# Source: the Sintel trailer, (c) Blender Foundation, CC-BY 3.0, served by W3C at
# a stable URL. https://durian.blender.org/  —  attribution belongs in any demo
# that ships a frame of it.
#
# Requires: curl, ffmpeg (brew install ffmpeg).

set -euo pipefail

cd "$(dirname "$0")/.."
mkdir -p devnotes/media

SRC=devnotes/media/sintel-trailer.mp4
URL=https://media.w3.org/2010/05/sintel/trailer.mp4

# 854x480 h264, 24 fps, 1253 frames, 52.2 s, with an AAC track — a real-world
# clip with real motion, real grain and a soundtrack we ignore.
if [ ! -f "$SRC" ]; then
  echo "fetching $URL"
  curl -fL --max-time 300 -o "$SRC" "$URL"
else
  echo "have $SRC"
fi

# A bright 5 s silent cut, with the source's baked letterbox bars removed. The
# old 20–25 s cut spent most of its run in near-black frames and wasted 27% of
# scarce terminal rows on black bars. 23–28 s stays bright through all 60 packed
# frames instead of ending on the trailer's black transition; the same crop is
# valid across the whole source.
ffmpeg -hide_banner -v error -y -ss 23 -t 5 -i "$SRC" \
  -vf "crop=848:352:4:64" -an -c:v h264_videotoolbox -b:v 1200k \
  devnotes/media/sintel-5s.mp4

# An animated GIF of the same three seconds, for whatever pure-JS decode path
# exists. palettegen/paletteuse rather than the default 256-colour dither, so the
# GIF's own quantisation isn't what we end up looking at.
ffmpeg -hide_banner -v error -y -ss 23 -t 3 -i "$SRC" \
  -vf "crop=848:352:4:64,fps=12,scale=240:-1:flags=lanczos,split[a][b];[a]palettegen[p];[b][p]paletteuse" \
  devnotes/media/sintel-3s.gif

ls -la devnotes/media/

# ─── The cinema demo's pack ───────────────────────────────
# demos/cinema/assets/sintel.tvf IS committed — a demo has to run from a fresh
# clone, and the mp4 it comes from does not. This regenerates it identically.
npx tsx scripts/tvf-pack.ts devnotes/media/sintel-5s.mp4 \
  demos/cinema/assets/sintel.tvf --fps 12

# ─── Committed fixtures ───────────────────────────────────
# Regenerate only on purpose: these are checked in, and changing them changes
# every byte-stable assertion made against them. testsrc2 is deterministic, so
# the same ffmpeg produces the same file, but a different ffmpeg may not.
if [ "${REGEN_FIXTURES:-0}" = "1" ]; then
  mkdir -p test/fixtures/video
  ffmpeg -hide_banner -v error -y -f lavfi -i "testsrc2=size=64x48:rate=10:duration=1" \
    -c:v libx264 -pix_fmt yuv420p -crf 30 test/fixtures/video/testsrc-64x48-10fps.mp4
  ffmpeg -hide_banner -v error -y -f lavfi -i "testsrc2=size=48x32:rate=8:duration=1" \
    -vf "split[a][b];[a]palettegen=max_colors=32[p];[b][p]paletteuse" \
    test/fixtures/video/testsrc-48x32-8f.gif
  echo "regenerated committed fixtures — check the diff before committing"
fi
